name: Firefox Build bundle package


on:
  workflow_dispatch:
    inputs:
      spark:
        description: 'Spark version: spark-3.2, spark-3.3, spark-3.4 or spark-3.5'
        required: true
        default: 'spark-3.5'
      hadoop:
        description: 'Hadoop version: 2.7.4, 3.2.0, 3.2.2, 3.3.1, 3.3.3 or 3.3.6'
        required: true
        default: '3.3.6'

jobs:
  build:
    runs-on: ubuntu-22.04
    container: ubuntu:jammy
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build Gluten velox
        run: |
          ln -snf /usr/share/zoneinfo/$CONTAINER_TIMEZONE /etc/localtime && echo $CONTAINER_TIMEZONE > /etc/timezone
          apt-get update
          apt-get install -y git sudo 
          ./dev/buildbundle-veloxbe.sh
      - name: Upload bundle package
        uses: actions/upload-artifact@v4
        with:
          name: gluten-velox-bundle-package
          path: package/target/gluten-velox-bundle-*.jar
          retention-days: 7
